### ISSUE TITLE
Consider adding GADM dataset to the datakit

### ISSUE THREAD

**Issue by ekatef** [pz-max/pypsa-africa#894] opened 2023-10-16 11:57 UTC
## Describe the feature you'd like to see

GADM server being down leads to serious troubles when installing and building the model, including a tutorial run. A solution discussed previously is to add GADM data to our datakit kept on zenodo/gdrive.

## Suggestions
I have investigated a bit this solution and prepared GADM dataset. It's overall size is 5.01 Gb unzipped. The following sanity checks have been run successfully:

- [x] local file size correspond to the size indicated on gadm server page;
- [x] all the locally stored files can be opened with geo-pandas without any troubles.

So, now we have some gadm backup, while it may be worth to integrate the dataset into out data management.

**Comment by davide-f** [comment] 2023-10-16 18:15
I think this is a duplicate of #889, shall we close this issue?

**Comment by ekatef** [comment] 2023-10-16 18:21
> I think this is a duplicate of #889, shall we close this issue?

No, it's not: #889 relates only to the tutorials, while here the idea here is to have a backup for all the countries. Would you approve?

**Comment by ekatef** [comment] 2023-10-16 18:27
Closed in favour #889

**Closed as completed** 2023-10-16 18:42 UTC
