### ISSUE TITLE
Building power plants error

### ISSUE THREAD

**Issue by oayana** [pz-max/pypsa-africa#154] opened 2021-11-20 16:03 UTC
While analyzing for Turkey, I encountered a new error (it looks like a "bad lines" error when reading csv dataset in pandas).

I get the error on line 91 inside the build_powerplants script:

https://github.com/pypsa-meets-africa/pypsa-africa/blob/509d2ba691c622c2245df63631c7f09c91089355/scripts/build_powerplants.py#L91

For these situations,  "error_bad_lines=False" is used  when reading the dataset in pandas. However, since the error comes directly from the "powerplantmatching" library, I don't know how to ignore this error.

Detailed error:
INFO:powerplantmatching.collection:Collect combined dataset for CARMA, GEO, GPD
WARNING:powerplantmatching.collection:Forcing update since the cache file is missing
Traceback (most recent call last):
  File "C:\Users\muh1\Desktop\pypsa\Pypsa_data\pypsa-africa\.snakemake\scripts\tmpzhd4s462.build_powerplants.py", line 95, in <module>
    ppl = (pm.powerplants(
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\site-packages\powerplantmatching\collection.py", line 255, in matched_data
    matched = collect(matching_sources, config=config, **collection_kwargs)
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\site-packages\powerplantmatching\collection.py", line 114, in collect
    dfs = parmap(df_by_name, datasets)
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\site-packages\powerplantmatching\utils.py", line 392, in parmap
    return list(map(f, arg_list))
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\site-packages\powerplantmatching\collection.py", line 83, in df_by_name
    df = get_df(config=config)
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\site-packages\deprecation.py", line 260, in _inner
    return function(*args, **kwargs)
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\site-packages\powerplantmatching\data.py", line 377, in CARMA
    carma = pd.read_csv(get_raw_file("CARMA", update, config), low_memory=False)
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\site-packages\pandas\io\parsers\readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\site-packages\pandas\io\parsers\readers.py", line 488, in _read
    return parser.read(nrows)
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\site-packages\pandas\io\parsers\readers.py", line 1047, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 228, in read
    data = self._reader.read(nrows)
  File "pandas\_libs\parsers.pyx", line 783, in pandas._libs.parsers.TextReader.read
  File "pandas\_libs\parsers.pyx", line 872, in pandas._libs.parsers.TextReader._read_rows
  File "pandas\_libs\parsers.pyx", line 1925, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 5, saw 3

Is there a solution for this?

**Comment by pz-max** [comment] 2021-11-20 16:36
@koen-vg could you advise when the powerplantmatching works globally?

**Comment by ekatef** [comment] 2021-11-22 07:26
Building `powerplants.csv` for Africa gives the same error. I have tried to change `powerplants_filter:` in the config file to use the custom power plants list only

```python
  powerplants_filter: false
  custom_powerplants: true
```
However, this seems do not change anything...

**Comment by pz-max** [comment] 2021-11-22 08:29
@ekatef, powerplants are not fully integrated so far I know so some functions are not active. 
@davide-f you played also a bit with that? Any other insights? @koen-vg is integrating powerplantmatching at the moment

**Comment by davide-f** [comment] 2021-11-22 09:52
I have tried working, but errors in osm_data_cleaning occurr, which shall be solved first

**Comment by davide-f** [comment] 2021-11-22 11:22
After solving the issues I encountered, I investigated this issue.
It turns out that the optional csv related to the raw data is not accounted for: the corresponding function add_custom_powerplants is disabled
That should be enabled to populate the data downloaded from OSM. To do so, there is the need to add in osm_data_cleaning a procedure to filter and standardize the powerplants csv according to the [powermatching format](https://github.com/FRESNA/powerplantmatching)

**Comment by ekatef** [comment] 2021-11-22 13:27
@pz-max  @davide-f Many thanks for giving the hints. 
I'm currrently trying to generate `powerplants.csv` from `africa_all_generators.csv` to get the `Snakefile` work until its' end. When this attempt will succeeded, I could propose a solution for the `osm_data_cleaning` script.

**Comment by davide-f** [comment] 2021-11-22 13:38
@ekatef Thank you! :)
The powerplants.csv file can be found in data/clean/africa_all_generators.csv. I have pushed a simple commit to update snakemake with the proper input.
I've also slightly changed build_powerplants to enable loading the custom csv.
However, the problem "WARNING:root:Couldn't find close bus for 115 powerplants" arises.
This shall be investigated, starting from the structure of africa_all_generators.csv to comply with the standard by powerplantmatching

**Comment by ekatef** [comment] 2021-11-25 09:15
@davide-f Many thanks for preparing the workspace and informing about the warning. It was very helpful. As it appears, the problem consists of some parts.

First, there were some troubles with initial settings of the `powerplantmatching`. I have had the same pandas error `> Expected 1 fields in line 5, saw 3` as @oayana has shown. This issue has been fixed by creating a config file for the `powerplantmatching` and adding some sources inside like this

```Python
matching_sources:
    - JRC
    - CARMA
```
After doing so, I have finely obtained the `Couldn't find close bus` warning you mentioned. It seems that it would be helpful to include into `pypsa-africa` tutorials a few words about initial settings of `powerplantmatching`.  Probably, it also makes sence to propose a PR related to this issue for `powerplantmatching`.

Secondly, I have tried to match OSM-extracted data with `powerplantmatching` requirements. The result was this [quick fix](https://github.com/ekatef/pypsa-africa/blob/9114b7b8266410f3c8bca7227580d90d75ac1ca3/scripts/build_powerplants.py#L72-L83)

```Python
    custom_ppls_coords = gpd.GeoSeries.from_wkt(raw_custom_ppls['geometry'])
    custom_ppls_data = {'Name':raw_custom_ppls['id'], 
    # TODO Improve correspondance with powerplantmatching fields
    'Fueltype':raw_custom_ppls['tags.generator:source'], 
    'Technology':(raw_custom_ppls['tags.generator:type'] + ', ' + raw_custom_ppls['tags.generator:method']), 
    'Set':raw_custom_ppls['tags.power'], 'Country':raw_custom_ppls['Country'], 
    'Capacity':raw_custom_ppls['power_output_MW'], 'Efficiency':'', 'Duration':'',
    'Volume_Mm3':'', 'DamHeight_m':'', 'StorageCapacity_MWh':'', 
    'DateIn':'', 'DateRetrofit':'', 'DateMothball':'','DateOut':'',
    'lat':custom_ppls_coords.y, 'lon':custom_ppls_coords.x,
    'EIC':'', 'projectID':''}
    add_ppls = pd.DataFrame(data=custom_ppls_data)
```

However, that is not a final solution, as I was not able to properly transform the OSM-derived columns values to match them with the conventions of `powerplantmatching`. For instance, should be "gas" always interpreted as "Natural Gas"? And is "gas_turbine" an open-cycle gas turbine ("OCGT") or could it be in some cases a combined-cycle block ("CCGT")? I would be grateful for some hints related to the philosophy behind the OSM data extraction. @pz-max Could you please advise where to have a  look or whom to ask? :-)

**Comment by pz-max** [comment] 2021-11-25 09:49
Hi Katia,
Cool that you delve into the powerplant part which is really not stable so far. I know that Koen tries to integrate OSM data directly into powerplantmatching. As I remember from the last exchange with him, there is not much work left. If you want to support him, I think he would be happy, please get in contact with him.

Regarding the second part. Open Street Map has some tag descriptions https://wiki.openstreetmap.org/wiki/Tag:generator:source%3Dgas . The generator:type in the link seems to clarify what information the gas generators should possess:
generator:type<https://wiki.openstreetmap.org/wiki/Key:generator:type>=*

  *   generator:type<https://wiki.openstreetmap.org/wiki/Key:generator:type>=gas_turbine<https://wiki.openstreetmap.org/wiki/Tag:generator:type%3Dgas_turbine>
  *   generator:type<https://wiki.openstreetmap.org/wiki/Key:generator:type>=combined_cycle<https://wiki.openstreetmap.org/wiki/Tag:generator:type%3Dcombined_cycle>
  *   generator:type<https://wiki.openstreetmap.org/wiki/Key:generator:type>=reciprocating_engine<https://wiki.openstreetmap.org/wiki/Tag:generator:type%3Dreciprocating_engine>
  *   generator:type<https://wiki.openstreetmap.org/wiki/Key:generator:type>=steam_generator<https://wiki.openstreetmap.org/wiki/Tag:generator:type%3Dsteam_generator>
  *   generator:type<https://wiki.openstreetmap.org/wiki/Key:generator:type>=steam_turbine<https://wiki.openstreetmap.org/wiki/Tag:generator:type%3Dsteam_turbine>

Regarding the if "gas" is always natural gas. Here are some tags that help understand what "generator:source" can mean https://wiki.openstreetmap.org/wiki/Key:generator:source. Hope that helps. 🙂
________________________________

**Comment by davide-f** [comment] 2021-11-25 09:50
Awesome @ekatef , good job! :)

My personal view, temporary, is to check whether we can make it run with a reasonable approach, when ambiguities are there.
Clearly, there are some ambiguities that we will investigate, and it is better to post here any non-trivial assumption.
As for the example you provided, I would go for the assumption "gas_turbine" -> OCGT , but maybe this is not unique, clearly.

As a comment, what we are trying to do, is something similar to what powerplantmatching (PPM) does internally.
Let me better explain. In PPM, each name listed in the sources must correspond to a specific function that downloads and convert the data in the appropriate format (file [data.py](https://github.com/FRESNA/powerplantmatching/blob/master/powerplantmatching/data.py) of PPM).
In that file you can find examples about how such conversion is made in other data sources, yet it is pretty similar to what you are discussing. OSM is a commented option in the current package; if we successfully do that, in the future we may push back the change to PPM.

@koen-vg has worked on that and implemented the first version of PPM for pypsa-africa. Actually, its package has been merged with the main PPM, thus we may change the dependency later on.

**Comment by ekatef** [comment] 2021-11-26 13:03
Hey @pz-max, hey @davide-f,

Many thanks for detailed explanations and the hints. They all are very helpful.

@pz-max Great to know that OSM integration into PPM is being under process. Then, that is definitely a good idea to contact Koen. Yes, the OSM tags are exactly what I needed. Thank you!

@davide-f Absolutely agree about writing the assumptions down. As far as I can see, that would be also a good idea to match my coding exercises with PPM practices. Thank you for the link to `PPM::data.py` and your suggestions!

**Comment by ekatef** [comment] 2021-12-07 15:25
The proposed fix implies some (rather arbitrary) assumptions, namely:

1. The benchmark PPM keys values were taken according to the PPM local testing as follows:

        'Fueltype': ['Hydro', 'Hard Coal', 'Natural Gas', 'Lignite', 'Nuclear', 'Oil', 'Bioenergy', 'Wind', 'Geothermal', 'Solar', 'Waste', 'Other'] 
        'Technology': ['Reservoir', 'Pumped Storage', 'Run-Of-River', 'Steam Turbine', 'CCGT', 'OCGT'
            'Pv', 'CCGT, Thermal', 'Offshore', 'Storage Technologies']
        'Set': ['Store', 'PP', 'CHP']

2. OSM-extracted features were mapped into PPM ones using a following set of rules:

       2.1. for fossil-fuelled generation
             'coal': 'Hard Coal'

       2.2. for wind generation
             'wind_turbine': 'Onshore',
             'horizontal_axis' : 'Onshore',
             'vertical_axis' : 'Offhore',

       2.3. for nuclear generation
           'nuclear': 'Steam Turbine'

3. All hydro OSM-extracted objects were interpreted as generation technologies, although ["Run-Of-River", "Pumped Storage", "Reservoir"] in PPM can belong to 'Storage Technologies', too. 

4. OSM extraction was supposed to be ignoring non-generation features like CHP and Natural Gas storage (in contrast to PPM).

Hopefully, we'll be able to improve it in the future :)

**Comment by ekatef** [comment] 2021-12-17 07:10
The `pd.replace()` and `pd.drop()` in the patch above do not work as expected. Sorry for that!

The correction is in this commit 4efd7e5bcc0b6b9205aa6a37e368785a5c207e73. If you think it's useful I can propose it as a PR.

**Comment by ekatef** [comment] 2021-12-17 07:13
The OSM tags extracted from https://wiki.openstreetmap.org/wiki/Key:generator:type:

'nuclear'
	'fission'
		'PWR', 'PWR', 'BWR-1', 'BWR-6', 'BWR-3', 'PHWR', 'GCR', 'FBR', 'RBMK-1000', 'RBMK-1500', 'RBMK-1000', 'VVER', 'CANDU', 'CPR-1000', 'EPR', 
	'fusion'
		'tokamak', 'stellarator', 'ICF', 'cold-fusion'

'wind'
	'wind_turbine'
		'horizontal_axis', 'vertical_axis'

'hydro'
	'water-storage'
		'francis_turbine', 'kaplan_turbine', 'pelton_turbine', 'hydrodynamic_screw', "Archimedes' screw"
	'water-pumped-storage'
		'francis_turbine'
	'run-of-the-river'
		'francis_turbine', 'kaplan_turbine', 'pelton_turbine'

'tidal'
	'barrage', 'kaplan_turbine'
	'stream', 'horizontal_axis', 'vertical_axis'

'wave'

'geothermal'
	'steam_turbine', 'heat_pump'

'solar'
	'thermal'
		'steam_turbine', 'solar_thermal_collector'
	'photovoltaic'
		'solar_photovoltaic_panel'

'coal'
	'combustion'
		'steam_turbine', 'steam_generator', 'boiler'

'gas'
	'combustion'
	'steam_turbine', 'gas_turbine', 'combined_cycle', 'reciprocating_engine', 'steam_generator', 'boiler'

'biomass'
	'combustion'
		'steam_turbine', 'steam_generator', 'boiler'
	'gasification'
		'bioreactor'
	'anaerobic_digestion'
		'bioreactor'

'biofuel'
	'combustion'
		'reciprocating_engine', 'steam_generator', 'boiler', 

'biogas'
	'combustion'
		'gas_turbine', 'steam_generator', 'reciprocating_engine', 'boiler'

'oil'
	'combustion'
	'steam_turbine', 'steam_generator', 'boiler'

'diesel'
	'combustion'
		'reciprocating_engine', 'steam_generator', 'boiler'

'gasoline'
	'combustion'
		'reciprocating_engine', 'steam_generator', 'boiler'

'waste'
	'combustion'
		'steam_turbine', 'steam_generator', 'boiler'

'battery'
	'battery storage'
		'lithium-ion', 'lead-acid', 'nickel-cadmium', 'redox_flow', 'molten-salt', 'boiler'

**Comment by pz-max** [comment] 2021-12-18 00:54
> The `pd.replace()` and `pd.drop()` in the patch above do not work as expected. Sorry for that!
> 
> The correction is in this commit [4efd7e5](https://github.com/pypsa-meets-africa/pypsa-africa/commit/4efd7e5bcc0b6b9205aa6a37e368785a5c207e73). If you think it's useful I can propose it as a PR.

Hi Katia, do you mind doing a pull request? I just checked out your fork and have some tips:
- 1. keep the `new-main` in your fork always updated (green button on the website of your fork saying something like contribute "fetch updates")
- 2. Only add features at the branch of your fork i.e. `git checkout -b ppm-bugfix`
- 3. Once you fix something you can also use the github GUI to contribute a PR (green button on the website of your fork saying something like contribute "Pull Request")

Let me know if you need help. Happy to support (I am occasionally in discord available - just having a terrible busy weekend)

**Comment by ekatef** [comment] 2021-12-20 08:04
Hi Max,

Yes, of course I'll be happy to contribute with a PR.
Many thanks for the hints related to git. They seem to work perfectly. 

Hope your weekend was a successful one :)

**Comment by davide-f** [comment] 2022-01-20 21:02
To update this old issue, I think that it should be appropriate to test this issue again from scratch by:
1. delete the environment pypsa-africa
2. delete the local pypsa-africa fork and fetch all the recent updates
3. start from scratch by cloning the repository and creating the environment

In the updates of the last month, the dependencies have been changed. In particular, the repository powerplantmatching used in the code has changed, thus it is difficult to say whether the same issue now remains.
I kindly recommend to do the above and post again if the issue is still there.

@oayana I think this updates may be in handy

**Comment by oayana** [comment] 2022-01-28 18:24
Hi @davide-f ,

First of all, thank you for your solution suggestion, but when I try it for Turkey, I still get the same error.

Here I am sharing the output of the console screen:
INFO:snakemake.logging:
INFO:pypsa.io:Imported network base.nc has buses, lines
INFO:powerplantmatching.collection:Collect combined dataset for CARMA, EXTERNAL_DATABASE, GEO, GPD
Traceback (most recent call last):
  File "C:\Users\muh1\Desktop\example\pypsa-africa\.snakemake\scripts\tmpetgsvb7n.build_powerplants.py", line 238, in <module>
    ppl = (pm.powerplants(
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\site-packages\powerplantmatching\collection.py", line 256, in matched_data
    matched = collect(matching_sources, config=config, **collection_kwargs)
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\site-packages\powerplantmatching\collection.py", line 115, in collect    dfs = parmap(df_by_name, datasets)
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\site-packages\powerplantmatching\utils.py", line 392, in parmap
    return list(map(f, arg_list))
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\site-packages\powerplantmatching\collection.py", line 83, in df_by_name
    df = get_df(config=config)
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\site-packages\deprecation.py", line 260, in _inner
    return function(*args, **kwargs)
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\site-packages\powerplantmatching\data.py", line 377, in CARMA
    carma = pd.read_csv(get_raw_file("CARMA", update, config), low_memory=False)
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\site-packages\pandas\io\parsers\readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\site-packages\pandas\io\parsers\readers.py", line 488, in _read
    return parser.read(nrows)
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\site-packages\pandas\io\parsers\readers.py", line 1047, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 228, in read
    data = self._reader.read(nrows)
  File "pandas\_libs\parsers.pyx", line 783, in pandas._libs.parsers.TextReader.read
  File "pandas\_libs\parsers.pyx", line 872, in pandas._libs.parsers.TextReader._read_rows
  File "pandas\_libs\parsers.pyx", line 1925, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 5, saw 3

[Fri Jan 28 21:18:10 2022]
INFO:snakemake.logging:[Fri Jan 28 21:18:10 2022]
Error in rule build_powerplants:
    jobid: 14
    output: resources/powerplants.csv, resources/powerplants_osm2pm.csv
    log: logs/build_powerplants.log (check log file(s) for error message)

ERROR:snakemake.logging:Error in rule build_powerplants:
    jobid: 14
    output: resources/powerplants.csv, resources/powerplants_osm2pm.csv
    log: logs/build_powerplants.log (check log file(s) for error message)

RuleException:
CalledProcessError in line 238 of C:\Users\muh1\Desktop\example\pypsa-africa\Snakefile:
Command 'C:/Users/muh1/.conda/envs/pypsa-africa/python.exe "C:\Users\muh1\Desktop\example\pypsa-africa\.snakemake\scripts\tmpetgsvb7n.build_powerplants.py"' returned non-zero exit status 1.
  File "C:\Users\muh1\Desktop\example\pypsa-africa\Snakefile", line 238, in __rule_build_powerplants
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\concurrent\futures\thread.py", line 58, in run
ERROR:snakemake.logging:RuleException:
CalledProcessError in line 238 of C:\Users\muh1\Desktop\example\pypsa-africa\Snakefile:
Command 'C:/Users/muh1/.conda/envs/pypsa-africa/python.exe "C:\Users\muh1\Desktop\example\pypsa-africa\.snakemake\scripts\tmpetgsvb7n.build_powerplants.py"' returned non-zero exit status 1.
  File "C:\Users\muh1\Desktop\example\pypsa-africa\Snakefile", line 238, in __rule_build_powerplants
  File "C:\Users\muh1\.conda\envs\pypsa-africa\lib\concurrent\futures\thread.py", line 58, in run
Removing output files of failed job build_powerplants since they might be corrupted:

**Comment by pz-max** [comment] 2022-01-28 19:14
YOUR MAIN ERROR MESSAGE:
**pandas.errors.ParserError: Error tokenizing data. C error:**

**Googling for this issues, I saw this note from [stackoverflow](https://stackoverflow.com/questions/18039057/python-pandas-error-tokenizing-data):**
I've had this problem a few times myself. Almost every time, the reason is that the file I was attempting to open was not a properly saved CSV to begin with. And by "properly", I mean each row had the same number of separators or columns.

Typically it happened because I had opened the CSV in Excel then improperly saved it. Even though the file extension was still .csv, the pure CSV format had been altered.

Any file saved with pandas to_csv will be properly formatted and shouldn't have that issue. But if you open it with another program, it may change the structure.

**The above StackOverflow link also shares alternative reasons for such error**

Some steps you can take:
0. Check if your code would work for Nigeria and Benin (if it breaks your environment or local download might be corrupted)
1. Try some Stackoverflow fixes
2. Update and clone your fork from scratch
3. Remove everything from your base conda (it should be clean anyways as otherwise, it can lead sometimes to errors). Remove the old pypsa-africa environment `conda remove env -n pypsa-africa`. Reinstall the pypsa-africa environment.
4. Last but not least, examine your csv data and check what is different compared to Nigeria or similar

**Comment by davide-f** [comment] 2022-02-17 21:29
@oayana any updates on this issue? Shall we close it?
Most likely it was related to the environment that was outdated

**Comment by oayana** [comment] 2022-02-18 07:26
> @oayana any updates on this issue? Shall we close it? Most likely it was related to the environment that was outdated

Hi @davide-f ,

First of all, @pz-max  thank you for your solution suggestions :) It was solved when I reinstalled the environment on another computer. You can close this issue. For now, I have come to the solution_all_networks script working in Turkey, there are no problem. 

Finally, build_renewable_profiles for hydro is now running.

**Closed as completed** 2022-02-18 07:26 UTC
